quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.langchain4j.openai.base-url=http://localhost:11434/v1
quarkus.langchain4j.openai.api-key=ignored
quarkus.langchain4j.openai.chat-model.model-name=qwen3.5:9b-mlx
quarkus.langchain4j.openai.chat-model.reasoning-effort=none
quarkus.langchain4j.timeout=30000
quarkus.langchain4