quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=gemma4:e4b-mlx
quarkus.langchain4j.ollama.chat-model.temperature=0.1
quarkus.langchain4j.ollama.chat-model.format=json
quarkus.langchain4j.ollama.chat-model.model-options.think=false
quarkus.langchain4j.timeout=30000