quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.langchain4j.ollama.base-url=${QADMIN_MODEL_URL}
quarkus.langchain4j.ollama.chat-model.model-id=${QADMIN_MODEL_ID}
quarkus.langchain4j.ollama.chat-model.temperature=${QADMIN_MODEL_TEMPERATURE}
quarkus.langchain4j.ollama.chat-model.format=json
quarkus.langchain4j.ollama.chat-model.model-options.think=false
quarkus.langchain4j.timeout=60s